name: app_pde
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.1+11

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter_keyboard_visibility: ^5.1.1
  modal_bottom_sheet: ^2.0.0

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  material_design_icons_flutter: ^5.0.5955-rc.1
  cloud_firestore: ^3.1.14
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.3
  equatable: ^2.0.3
  firebase_auth: ^3.0.1
  firebase_database: ^9.0.13
  flutter_mobx: ^2.0.1
  flutter_modular: ^3.3.1
  flutter_spinkit: ^5.0.0
  json_annotation: ^4.0.1
  mask_text_input_formatter: ^2.0.0
  mobx: ^2.0.3
  firebase_core: ^1.4.0
  auto_size_text: ^3.0.0-nullsafety.0
  intl: ^0.17.0
  google_sign_in: ^5.0.7
  local_auth: ^2.0.2
  flutter_secure_storage: ^5.0.2
  date_time_picker: ^2.1.0
  file_picker: ^4.5.1
  cloud_functions: ^3.0.5
  flash: ^2.0.1
  firebase_storage: ^10.0.1
  path_provider: ^2.0.2
  flutter_downloader: ^1.7.1
  permission_handler: ^9.2.0
  image_picker: ^0.8.5
  open_file: ^3.2.1
  flutter_html: ^2.1.1
  url_launcher: ^6.0.9
  flutter_launcher_icons: ^0.9.1
  ntp: ^2.0.0
  firebase_messaging: ^11.1.0
  flutter_local_notifications: ^9.5.2
  timezone: ^0.8.0
  flutter_flavorizr: ^2.1.0
  dartz: ^0.10.1
  email_validator: ^2.0.1
  cpf_cnpj_validator: ^2.0.0
  android_path_provider: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.0
  flutter_modular_test: ^1.0.1
  json_serializable: ^6.1.1
  mobx_codegen: ^2.0.1+3
  modular_codegen: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#ff333333"
  adaptive_icon_foreground: "assets/images/image.png"

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:
  flavors:
    dev:
      app:
        name: "App dev"
      android:
        applicationId: "br.com.professordeengenharia.app"
        icon: "assets/images/icon.png"
        firebase:
          config: ".firebase/dev/google-services.json"
      ios:
        bundleId: "br.com.timetime.app-pde"
        icon: "assets/images/icon.png"
        firebase:
          config: ".firebase/dev/GoogleService-Info.plist"
    prod:
      app:
        name: "Professor de Engenharia"
      android:
        applicationId: "br.com.professordeengenharia.app"
        icon: "assets/images/icon.png"
        firebase:
          config: ".firebase/prod/google-services.json"
      ios:
        bundleId: "br.com.timetime.apppde"
        icon: "assets/images/icon.png"
        firebase:
          config: ".firebase/prod/GoogleService-Info.plist"